export const ADD_TODO = 'ADD_TODO'
export const UPDATE_TODO = 'UPDATE_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const ADD_USERNAME = 'ADD_USERNAME'
export const SET_INITIAL_STATE = 'SET_INITIAL_STATE'